### ISSUE TITLE
Drop down staying expanded and aligned wrongly

### ISSUE THREAD

**Issue by aswinfrancis91** [PowerKiKi/ie_expand_select_width#5] opened 2014-11-03 13:35 UTC
![untitled](https://cloud.githubusercontent.com/assets/1233653/4883020/b649b814-635d-11e4-8932-67408733f76b.jpg)
I have added the plugin and call it on a drop down in one of the page i am creating. The functionality of the page is as follows. Once the user selects the values he needs from some mandatory fields including the one which  calls this plugin, he will click Save. After saving the user will be shown a message that the item has been created/updated. When user clicks OK in this message the same page would be shown but in view mode. I.e. the fields will be disabled with the values user had selected in edit mode. Now during edit the drop down works fine. 

After clicking Save and when the field goes into view mode the expanded drop down starts showing somewhere on the top corner in disabled mode. The original drop down will be in its own position as it is supposed to be without any problem. But the expanded drop down will also appear somewhere else on the screen. This location is not fixed and this doesn't happen all the time. What could be the reason for this?

**Comment by PowerKiKi** [comment] 2014-11-03 14:35
Is it a full page reload or the save is done via ajax and then you alter DOM via javascript ?

**Comment by aswinfrancis91** [comment] 2014-11-03 14:43
Ajax call and then use javascript to disable the field.. I can set the top value of the field to zero to hide it but I don't want the duplicates to be created 
Sent using CloudMagic
On Mon, Nov 03, 2014 at 8:05 pm, PowerKiKi notifications@github.com wrote:Is it a full page reload or the save is done via ajax and then you alter DOM via javascript ?

**Comment by PowerKiKi** [comment] 2014-11-03 15:05
Hard to tell without code, but would it be possible that you call the plugin several times ? Especially after save ?

If I understand correctly you would like the plugin to completely disabled if the select element is disabled ?

Can you create a plunkr with your issue ?

**Comment by aswinfrancis91** [comment] 2014-11-04 06:31
I'm sorry but i cannot share the code. If disabling the plugin is the only way then that would also help. The thing is it doesn't always happen this way. At times only it happens and there is no special ways to replicate it. Maybe if i can add a class to the clones that are created, then on save maybe I can remove all elements with that class name?

**Comment by PowerKiKi** [comment] 2014-11-04 06:53
I won't be able to give you precise instructions without a reproducible case, but you could try something with `ie_expand_select_width_ignore`. It is a flag that is used internally to disable the plugin in specific cases. So I guess you could set that flag yourself and that should disable the plugin for that element.

To get an idea how to do that, have a look at https://github.com/PowerKiKi/ie_expand_select_width/blob/gh-pages/javascripts/ie_expand_select_width.js#L52

**Comment by aswinfrancis91** [comment] 2014-11-04 07:21
Even i am struggling as i cannot replicate it. It happens at time and the testing team raises it as an issue. Even for them it doesnt happen all the time. So how do i use the flag?I want the clones to be removed when it is in view mode, i.e after save.

Can I set a class to the clones so i can remove them on view mode?Is that a good way to do it?

**Comment by PowerKiKi** [comment] 2014-11-04 07:27
Setting the flag right after the save (or even just before) should prevent the plugin to create new clones. 

The clones don't have any special classes. The only way to get the clones is to get the original select element and access the `ie_expand_select_width_clone` data as seen in https://github.com/PowerKiKi/ie_expand_select_width/blob/gh-pages/javascripts/ie_expand_select_width.js#L37

**Comment by aswinfrancis91** [comment] 2014-11-04 09:51
I think i got a temporary fix set up.As i could not replicate the issue, i commented the lines of code from your plugin that removed the clone so that i can try the fix. What i did is, in line 45 of your code, i am adding a class 'cloneClass' to the clone created and then on Save function i am removing elements with this temporary class. It seemed to work as intended. Do you think this is ok?

**Comment by PowerKiKi** [comment] 2014-11-05 02:01
You are fixing the symptom rather than the cause, which is suboptimal, but if it works for you, then fine. I won't be able to help you more than that without a reproducible case.

For the time being I'll close this issue, since you got a workaround, but feel free to re-open if you manage to reproduce the case.

**Closed as completed by PowerKiKi** 2014-11-05 02:01 UTC

**Comment by aswinfrancis91** [comment] 2014-11-05 06:26
I commented off the remove clone code from the plugin to force the issue to happen and see if the workaround works. It did. If i can replicate normally i will update you on the steps. Thanks a lot for your help and for this helpful plugin :)
